name: Update e4

on:
  schedule:
    - cron:  '1,11,21,31,41,51 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Fetch the new key
        run: curl "https://e4-key.themoviearchive5408.workers.dev/" > $GITHUB_WORKSPACE/e4.json

      - name: Commit report
        run: |
          git config --global user.name 'BlackVid'
          git config --global user.email 'blackvid@users.noreply.github.com'
          if git commit -am "Updated e4"; then
            git push
          else
            echo No changes
          fi

